language: ruby

rvm:
  - 2.0.0

before_install:
  - gem --version

script:
  - sudo gem install fpm-cook
  - sudo fpm-cook install-deps
  - bundle install
  - bundle exec fpm-cook --version
  - PATH=$PATH bundle exec rake build
