language: ruby

rvm:
  - 2.0.0

before_install:
  - gem --version

script:
  - bundle exec fpm-cook --version
  - sudo yum install -y ruby-devel
  - sudo gem install bundler
  - sudo bundle
  - sudo bundle exec fpm-cook install-deps
  - PATH=$PATH bundle exec rake build
