task :default do
  system 'fpm-cook'
  system %W[
    fpm
    -s             dir
    -t             rpm
    -C             tmp-build
    --architecture noarch
    --version      3.0.0
    --category     databases
    --depends      mono
    --maintainer   developer@intelliplan.se
    --vendor       Intelliplan_International_AB
    --name         eventstore
    --prefix       /opt/eventstore
    --url          https://github.com/EventStore/EventStore
    --force
    .
  ].join(' ')
end
